server:
  port: 8085

spring:
  data:
    mongodb:
      username: root
      password: pwd
      database: admin
      host: localhost
      port: 27017

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, metrics
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: true

logging:
  level:
    root: INFO
  pattern:
    level: "[%X{MDC_KEY}] %5p"
